service: password-validator
app: password-validator-app

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-2

functions:
  password:
    handler: handler.password
    events:
      - http:
          path: password/{password}
          method: get
plugins:
  - serverless-offline
